sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_install:
  - npm i -g npm@latest
  - npm i -g codeclimate-test-reporter
before_script:
  - npm prune
after_success:
  - npm run semantic-release
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
