language: node_js
node_js:
  - "iojs"

notifications:
  email: false

cache:
  directories:
    - node_modules

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install -g codeclimate-test-reporter

after_script:
  - npm run reduct publish-coverage